[package]
name = "qraft_derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.101", features = ["extra-traits", "fold", "full", "test", "visit", "visit-mut"] }
